[project]
name = "veryfi-takehome-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "pillow>=11.1.0",
    "requests>=2.32.3",
    "sqlmodel>=0.0.24",
]
